### ISSUE TITLE
Highlighting a table even when the spec is not executed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#101]
**Expected behavior**
The table should be green/red only when the spec is executed.

**Actual behavior**
It is being highlighted even without execution.

**Steps to replicate**
1. Create a spec
```
with Table Params
=====================
     |table_Gauge_param|table_hi_param|
     |-----------|--------|
     |a          |b       |

* sdfsdfsdf

To refactor
----------------

* sdf
* abc
* Say <table_hi_param> to "Gauge"
_____________________________
* Say <table_Gauge_param> to "Gauge"
```
2. Create an implementation
```
    @Step("Say <Hello> to <Gauge>")
    public void implementation3(String argHello, String argGauge) {
    }
```
3. Run the spec
See the table is being highlighted even without the spec being executed.

<img width="1034" alt="highlight_without_execution" src="https://cloud.githubusercontent.com/assets/6310197/19995973/0f047a42-a282-11e6-914d-dbb5315636b6.png">

**Version**
```
Gauge version: 0.6.3.nightly-2016-10-27

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-27)
java (0.5.1.nightly-2016-10-26)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by apoorvam** [comment]
**Dev notes:**

> when the entire spec is skipped, all the table rows are still green.

In order to fix above issue, changes has to be done in Gauge-core.

When a table-driven spec is skipped for steps being unimplemented, the field `IsTableDriven` in `ProtoSpec` is not set to `true`. It retains the default value of bool, false. 

Also, the scenario results for all the table rows is not updated. The method `SkipSpec()` [here](https://github.com/getgauge/gauge/blob/ed6486deb4e6b3cfb73d3a903b0bbe69b552ea6a/execution/specExecutor.go#L213) uses `specResult.AddScenarioResults()` method, whereas in case of table driven spec it should use `specResult.AddTableDrivenScenarioResult()` to update all fields.

**Comment by sguptatw** [comment]
Another thing to be taken care of is when I click the skipped row, I should be able to see the details of the spec.

**Comment by BugDiver** [comment]
The fix should be available in nightly > 10-01-2107.

**Comment by sriv** [comment]
Closing as stale. Please reopen if this is still valid.
