### ISSUE TITLE
Performance issues in report generation

### ISSUE THREAD

**Issue by BugDiver** [getgauge/html-report#121]
Currently, if there are 1000 specs with just sample scenario that comes with template, the execution finishes in 3-5 seconds. However the html-report plugin takes more than 50 seconds to generate reports. This should be optimized. 

### Notes: 
* Each spec takes 0.05 seconds to execute, so for 1000 specs its taking 50 seconds to generate reports.
* We could parallelize the HTML pages generation for specs.

Ref issue: #120

**Comment by apoorvam** [comment]
### Notes: 

* The golang html [templates](https://github.com/getgauge/html-report/blob/8baf6971c00ca2972c47c7b80761f5b716896146/generator/templates.go) has to be parsed first and then we execute it. So far we were parsing each and every template irrespective of how many times we will have to execute this. With [this commit](https://github.com/getgauge/html-report/commit/8baf6971c00ca2972c47c7b80761f5b716896146) the parsing of all templates is done initially so that we need not parse the same template multiple times. 
With this change, **the time for 1000 specs generation has come down to around 10-11 seconds**.

* Execution of templates is the most time-consuming event in the generation of HTML page for each spec. Currently, we have split the HTML page for each spec into a number of templates. We could see if we can merge a few wherever applicable.

**Comment by apoorvam** [comment]
### Notes: 

* Parallelized the generation of index file in [this](https://github.com/getgauge/html-report/commit/99ce296109b71046fc9b64f0505a9e4282751e14) commit
* The `html/template` rendering code uses reflection and is not as fast as statically compiled code. We had earlier used this pkg to avoid escaping data manually since html pkg automatically escapes HTML/JS elements.
Due to performance issues, we are now using `text/template` pkg and supplying it with escaped data. With these changes, the **report generation time has come down to around 4-6 seconds for 1000 specs**
(on MacOS Sierra)

**Comment by apoorvam** [comment]
Fix should be available in nightly >= 5.1.2017

**Comment by apoorvam** [comment]
Tested this and is working as expected.
