### ISSUE TITLE
Test cases in Gauge Report

### ISSUE THREAD

**Issue by vikyad** [getgauge/html-report#156]
How can I get test case related data in my gauge report i.e every row in the csv file from which data is being fetched in considered as a test case. Currently I am getting spec wise report.

**Comment by kashishm** [comment]
@vikyad You can click on the row to see its scenarios and the data passed to it.

**Comment by vikyad** [comment]
Actually, I want to get the total number of test cases passed and failed in the report like we get for specs.

Thanks,
Vikas

**Comment by pwlequifax** [comment]
This has definitely been fixed in the latest version. However, the number of scenarios that have passed or failed is incorrect. The total count is correct.

The example included has table driven scenarios.

![image](https://user-images.githubusercontent.com/41427079/51524943-22540400-1e27-11e9-94eb-b0fbb73bc6c8.png)

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
