### ISSUE TITLE
Customize Gauge HTML Report to have Platform, Browser

### ISSUE THREAD

**Issue by sudhindra-aithal** [getgauge/html-report#254]
I am looking to add these details in report.html in "report_details" section

### Expected behavior
How to add these details in Gauge Report
Platform - iOS, Android, Windows 
Browser - Firefox, Chrome

### Actual behavior
Gauge report only shows Environment data.

### Steps to reproduce
1. Run the script
2. View the report generated

### Gauge version
```
Gauge version: 1.0.7

Plugins
-------
html-report (4.0.9)
java (0.7.4)
screenshot (0.0.1)

```

**Comment by alpha1592** [comment]
I would also like to add the version of gauge and HTML report plugin used to run the test and generate the report. This is helpful if we want to recreate the same conditions for a test a year from now.

‘’’
Gauge: v1.0.7
HTML Report: v4.0.9
‘’’

**Comment by sriv** [comment]
Although you can customize the html report by changing/using a custom theme, in this case that might not be enough, since the plugin does not expose this data. 

I suppose having a provision to include custom meta-data would make sense? 

There are some information that Gauge/html-report can publish i.e version, platform executed on etc. However since the tools are framework agnostic, the next level of detail should be set by the test code (ex. browser used).

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
