### ISSUE TITLE
Rows in table driven scenario are wrongly linked

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/html-report#64]
### Expected behavior

In a table driven scenario, when a user clicks on a row, reports should show details for that particular row.
### Actual behavior

In a table driven scenario, when a user clicks on a row, reports are show details for some other row.
### Steps to reproduce
1. Create a new table driven spec.
2. Run a few rows of the table excluding the first row. So, something like `gauge --table-rows="3-7" specs`

**Comment by mahendrakariya** [comment]
Dependent on https://github.com/getgauge/gauge/issues/363

**Comment by apoorvam** [comment]
The dependent issue getgauge/gauge#363 is fixed and this is implemented in [commit](https://github.com/getgauge/html-report/commit/672188c6a2a8b37059557047ec72cce00fbd9131).

Fix should be available in nightly >= 26.10.2016

**Comment by sguptatw** [comment]
when the entire spec is skipped, all the table rows are still green. Another thing to be taken care of is when I click the skipped row, I should be able to see the details of the spec.
```
Specification Heading
=====================
tags: top

     |table|d1|d2|3d|d|
     |-----|--|--|--|-|
     |d    |d |  |d |d|
     |d    |d |  |d |d|
     |d    |d |  |d |d|
     |d    |d |  |d |d|

* volume
c
-
tags: scenario3 ppp a b c d e f g h i j k l m n o p q r s t u v w x y z

* Criaçãosdf

c1
--
tags: scenario3 ppp a b c d e f g h i j k l m n o p q r s t u v w x y z

* pass
mhvbmh
___
* pass
```

**Comment by apoorvam** [comment]
**Dev notes:**

In order to fix this, changes has to be done in Gauge-core.
When a table-driven spec is skipped for steps being unimplemented, the field `IsTableDriven` in `ProtoSpec` is not set to `true`. It retains the default value of bool, false. 

Also, the scenario results for all the table rows is not updated. The method `SkipSpec()` [here](https://github.com/getgauge/gauge/blob/ed6486deb4e6b3cfb73d3a903b0bbe69b552ea6a/execution/specExecutor.go#L213) uses `specResult.AddScenarioResults()` method, whereas in case of table driven spec it should use `specResult.AddTableDrivenScenarioResult()` to update all fields.

**Comment by apoorvam** [comment]
> when the entire spec is skipped, all the table rows are still green.

This particular case is already tracked in issue #101. So this can be closed?
