### ISSUE TITLE
Html report getting errors because of blocked scripts

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#68]
### Expected behavior
I should be able to see the report on the server without any js issues

### Actual behavior
JS is getting blocked which gives a lot of errors

### Steps to reproduce
1. Configure Jenkins to run gauge-tests
2. Check the reports
3. 
```
index.html:1 Blocked script execution in 'http://localhost:8080/job/GetGauge/ws/reports/html-report/index.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
html-report (2.1.0)
java (0.4.0.nightly-2016-05-09)
ruby (0.2.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by kaustavdm** [comment]
From the error message posted above, it looks like Jenkins loads reports in an `iframe` with script execution disabled. This means no JavaScript code will be allowed to evaluate in the context of that frame. The current version of `html-report` depends heavily on JavaScript. It is a "single page app" written with Angular JS. `html-report` at this point can work locally, i.e. loaded straight from disk by opening the generated `index.html` in your browser, but you need to allow script execution in the browser.

`html-report` does not perform any write operations on the disk and does not deal with cookies. It simply uses JavaScript to render the content that is put in a JSON file during the report generation.

GoCD reports tab shows `html-report` perfectly, FTW. I would call this issue a `wontfix` as this is more of an issue (security measure?) in Jenkins, rather than `html-report`.
