### ISSUE TITLE
Remove dependency on AngularJS

### ISSUE THREAD

**Issue by apoorvam** [getgauge/html-report#86]
## Current State

AngularJS is currently used for generating HTML reports. 

After the execution is completed, Gauge core invokes the html-report plugin and sends across the entire suite execution result via protobuf. This is converted to a JSON object which is used to render reports using AngularJS.

The downsides of this approach are

  * The entire JSON file (detailed suite result) gets loaded the first time reports are opened. This JSON file can run into MBs if the test suite has a lot of specs. This significantly increases the time to first load.
  * The reports only present a summary on first load. Entire data isn't needed initially.
  * There is a lot of business logic on HTML side to render different parts of the page. This is an anti-pattern. The business logic should ideally go to controller / service.

## Finalized Approach

Solution to these issues is to generate static HTML pages and remove AngularJS from the tech stack. 

### High Level Design

  * Move away from the Single Page Application model.
  * Create a static HTML page for each spec and inter link these pages with the `href` tag.
  * When Gauge core sends the suite execution result, use the data to directly generate static HTML pages.
  * Result won't be dumped to an intermediate JSON format.

### Implementation Details
  * Refer Angular templates and create Golang templates using [`text/template`](https://golang.org/pkg/text/template/) package.
  * Generate static HTML page, one for each spec using these templates and the suite execution result obtained from Gauge core.
  * Each page will have a copy of the common elements like sidebar, header, footer, summary, etc. (Refer the annotated screenshot below.) The code for these elements will be duplicated across all pages. Since it is auto generated, duplicate code shouldn't be a concern.
  * When users click on pass / fail / skip count in the overview, show / hide the `li` in the sidebar using javascript.
  * Link the elements in the sidebar to appropriate generated HTML pages.
  * The pie chart in the overview and the hover card for external files have a dependency on Angular. These elements will have to be redone from scratch.
  * Create an index (maybe using tf-idf) for search.

![screen shot 2016-07-13 at 1 31 50 pm](https://cloud.githubusercontent.com/assets/2538874/16796205/04265ad2-48ff-11e6-8a9d-d192cf415d68.png)

**Out of scope:**

  * When user filters specs by clicking on the pass / fail / skip count in the overview and then clicks on some spec in the sidebar, the filtered state should be maintained. This will be currently out of scope. It can be done along with #42.

### Refactor code and retain Angular

  * If Angular is retained, the entire JSON will still have to be loaded when user first opens the reports.
  * One approach would be to refactor existing code to move business logic from HTML side to controller. The business logic is mainly parsing JSON, formatting data, and figuring out what data is present. There is no need to do this every time report is loaded. This information is present even before the reports are generated. It can be utilized at the generation time.
  * Angular is only used for doing dynamic DOM manipulation. None of the other Angular features are utilized. Moreover, there is no dynamic data in the reports. All data is available upfront before reports are generated. So why do dynamic DOM manipulation at all?

### Other implementation approaches

  * Instead of duplicating code for sidebar, overview, header, footer, etc across all pages, we can have one page with the common code and separate pages for each spec. These spec pages will be loaded in an `iframe` or something similar in the main area. But using `iframe` is not a good idea. Moreover, duplicate auto generated code isn't a concern.
  * To retain pass / fail / skip filtering state across pages, two copies of each page could be created. One copy with full sidebar and one copy with filtered sidebar. (Notice that sidebar appearance is the only difference between filtered and unfiltered state). But this will be bit overcomplicated approach to retain the state. Alternative approaches needs to be thought about to retain state across pages.

**Comment by mahendrakariya** [comment]
## Current State

AngularJS is currently used for generating HTML reports. 

After the execution is completed, Gauge core invokes the html-report plugin and sends across the entire suite execution result via protobuf. This is converted to a JSON object which is used to render the reports using AngularJS.

The downsides of this approach are

  * The entire JSON file (detailed suite result) gets loaded the first time reports are opened. This JSON file can run into MBs if the test suite has a lot of specs. This significantly increases the time to first load.
  * The reports only present a summary on first load. So much data isn't needed initially.
  * There is a lot of business logic on HTML side to render different parts of the page. This is an anti-pattern. The business logic should ideally go to controller / service.

## Finalized Approach

Solution to these issues is to generate static HTML pages and remove AngularJS from the tech stack. 

### High level design

  * Move away from the Single Page Application model.
  * Create a static HTML page for each spec and inter link these pages with the `href` tag.
  * When Gauge core sends the suite execution result, use the data to directly generate static HTML pages.
  * Result won't be dumped to an intermediate JSON format.

### Implementation Details
  * Refer Angular templates and create Golang templates using [`text/template`](https://golang.org/pkg/text/template/) package.
  * Generate static HTML page, one for each spec using these templates and the suite execution result obtained from Gauge core.
  * Each page will have a copy of the common elements like sidebar, header, footer, summary, etc. (Refer the annotated screenshot below.) The code for these elements will be duplicated across all pages. But since it is auto generated, duplicate code shouldn't be a concern.
  * When users click on pass / fail / skip count in the overview, show / hide the `li` in the sidebar using javascript.
  * The elements in the sidebar will be linked to appropriate generated HTML pages.
  * The pie chart in the overview and the hover card for external files are dependent on the presence of Angular. These elements will have to be redone from scratch.
  * Create an index (maybe using tf-idf) for search.

![screen shot 2016-07-13 at 1 31 50 pm](https://cloud.githubusercontent.com/assets/2538874/16796205/04265ad2-48ff-11e6-8a9d-d192cf415d68.png)

**Out of scope:**

  * When user filters specs by click on the pass / fail / skip count in the overview and then clicks on some spec in the sidebar, the filtered state should be maintained. This will be currently out of scope. It can be done along with #42.

## Other Approaches

This section gives an overview of other approaches that were considered and why they were rejected.

### Refactor code and retain Angular

  * One approach would be to refactor existing code to move business logic from HTML side to controller. The business logic is mainly parsing JSON, formatting data, and figuring out what data is present. There is no need to do this every time report is loaded. This information is present even before the reports are generated. It should be utilized at the generation time.
  * Angular is only used to doing dynamic DOM manipulation. None of the other Angular features are utilized. Moreover, there is no dynamic data in the reports. All data is available upfront before reports are generated. So why use a framework for doing heavy dynamic DOM manipulation?

### Other implementation approaches

  * Instead of duplicating code for sidebar, overview, header, footer, etc across all pages, we can have one page with the common code and separate pages for each spec. These spec pages will be loaded in an `iframe
